apiVersion: apps/v1
kind: Deployment
metadata:
  name: photobomb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photobomb
  template:
    metadata:
      labels:
        app: photobomb
    spec:
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: example-dataset
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: nginx-storage

