apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: flask
spec:
  entryPoints:
    - flask
  routes:
    - match: HostSNI("magnus.pepiniere.cloudns.ch")
      service:
      - name: flask
        port: 80

